


strand = "CACTCCTAGTTAAGGCGACGCTCGCCCGAACGAAACAAGAATATTCGGTGGTGGCTTCAGTACACACCGGACATGCGGAACCCGCACTCAATTGTTCCGACAGTAGTATTCGTTGTGCCATCCAAGCCTTGCCATATGACTCTTCTGCATAAAGATGGCTTTCGGCTAGACGAAGTGTACGATCATCGTTCTTTTTATCGTCTTAGCATCAGTTTATGCGTCAGTGTGAACTCTAAAGCTACAGATTTGAGTATACCATAGCCGGAGCCAAGATTCGTCGACTGCTAATGGGGGTCCGGAAAGGGTGCTAGGTCCCGGGACAGCCGCTTACAGATTTGGCAATGACAATCTCGGGTACTGCGTAAGCACTTGGCTTGAGCGGGCCTCACACAATTGTAGGCATGGAAAGCCGCTTTATACACTAGATTGTCTAATCTTTACGTGCTTTGGAGCGCCCCACCTATTCGGGTCTGTAACTTGTTGTTACTTACAAGTTGCGAAATCCCAATGATTCCATGCCATTGGGAAACACTACTAATAGGGGGAACGGATCGACGGGCGAGCCCTATGGAGCTTCGTGGGTGATCGGGTGTACGCAAATCCCTGTAAATTCAGGATGCCGAGTTGCTACACAAAAGTGGTCGAAGTGCCCTCGCAATATACCAGAAACATGGCCATGGCGCATCACTAGCGGGTCTTGAACTCGTTAGGACAGGATCGTAATGGATTCAACCCATAAAGCGTAGTCAGTATATTGGGGGCCCGTCAATACAACCACGAGGGAACGTTAGACATTTCTGGGAAAACTATCGCTCGATACCGTAAGGCTTACCGCCGGAAGTCGCAGGTAACCAAAGCCACGGGACAGGGTCAAGATCGTTCCGTAAAAGGTACTCTTATGCCCGTGACACGACTCACGAGGGCGCTCCGTACGCCGGGGGAACTGCCACTATGGGCTCTCATGAAGCGA"



def reverse(s):
    return s[::-1]


def complement(n):
    for letter in n:
        if letter == 'A':
            print( 'T', end = ''),
        elif letter == 'C': 
            print('G', end = ''),
        elif letter == 'T': 
            print( 'A', end = ''),
        elif letter == 'G': 
            print('C', end = '')


            

                
         

#[::x-1] slices the function at the end and then reverses the order 

#complement("AAAACCCGGT") | reverse()


#complement(strand) 

print(reverse(("GTGAGGATCAATTCCGCTGCGAGCGGGCTTGCTTTGTTCTTATAAGCCACCACCGAAGTCATGTGTGGCCTGTACGCCTTGGGCGTGAGTTAACAAGGCTGTCATCATAAGCAACACGGTAGGTTCGGAACGGTATACTGAGAAGACGTATTTCTACCGAAAGCCGATCTGCTTCACATGCTAGTAGCAAGAAAAATAGCAGAATCGTAGTCAAATACGCAGTCACACTTGAGATTTCGATGTCTAAACTCATATGGTATCGGCCTCGGTTCTAAGCAGCTGACGATTACCCCCAGGCCTTTCCCACGATCCAGGGCCCTGTCGGCGAATGTCTAAACCGTTACTGTTAGAGCCCATGACGCATTCGTGAACCGAACTCGCCCGGAGTGTGTTAACATCCGTACCTTTCGGCGAAATATGTGATCTAACAGATTAGAAATGCACGAAACCTCGCGGGGTGGATAAGCCCAGACATTGAACAACAATGAATGTTCAACGCTTTAGGGTTACTAAGGTACGGTAACCCTTTGTGATGATTATCCCCCTTGCCTAGCTGCCCGCTCGGGATACCTCGAAGCACCCACTAGCCCACATGCGTTTAGGGACATTTAAGTCCTACGGCTCAACGATGTGTTTTCACCAGCTTCACGGGAGCGTTATATGGTCTTTGTACCGGTACCGCGTAGTGATCGCCCAGAACTTGAGCAATCCTGTCCTAGCATTACCTAAGTTGGGTATTTCGCATCAGTCATATAACCCCCGGGCAGTTATGTTGGTGCTCCCTTGCAATCTGTAAAGACCCTTTTGATAGCGAGCTATGGCATTCCGAATGGCGGCCTTCAGCGTCCATTGGTTTCGGTGCCCTGTCCCAGTTCTAGCAAGGCATTTTCCATGAGAATACGGGCACTGTGCTGAGTGCTCCCGCGAGGCATGCGGCCCCCTTGACGGTGATACCCGAGAGTACTTCGCT")))




